dist: xenial
language: scala
jdk: openjdk8

scala:
  - 2.12.10

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - ci/checksourcemaps.sh
